const roomKey = {
  2: { timeOfDay: "DAY", room: "BRUT" },
  3: { timeOfDay: "DAY", room: "BRUT" },
  4: { timeOfDay: "DAY", room: "BRUT" },
  5: { timeOfDay: "NIGHT", room: "BRUT" },
  6: { timeOfDay: "NIGHT", room: "BRUT" },
  7: { timeOfDay: "NIGHT", room: "BRUT" },
  8: { timeOfDay: "DAY", room: "GALLERY" },
  9: { timeOfDay: "DAY", room: "GALLERY" },
  10: { timeOfDay: "DAY", room: "GALLERY" },
  11: { timeOfDay: "NIGHT", room: "GALLERY" },
  12: { timeOfDay: "NIGHT", room: "GALLERY" },
  13: { timeOfDay: "NIGHT", room: "GALLERY" },
  14: { timeOfDay: "DAY", room: "TERRACE" },
  15: { timeOfDay: "DAY", room: "TERRACE" },
  16: { timeOfDay: "DAY", room: "TERRACE" },
  17: { timeOfDay: "NIGHT", room: "TERRACE" },
  18: { timeOfDay: "NIGHT", room: "TERRACE" },
  19: { timeOfDay: "NIGHT", room: "TERRACE" },
  20: { timeOfDay: "DAY", room: "WAREHOUSE" },
  21: { timeOfDay: "DAY", room: "WAREHOUSE" },
  22: { timeOfDay: "DAY", room: "WAREHOUSE" },
  23: { timeOfDay: "NIGHT", room: "WAREHOUSE" },
  24: { timeOfDay: "NIGHT", room: "WAREHOUSE" },
  25: { timeOfDay: "NIGHT", room: "WAREHOUSE" },
  26: { timeOfDay: "DAY", room: "HOT HOUSE" },
  27: { timeOfDay: "DAY", room: "HOT HOUSE" },
  28: { timeOfDay: "DAY", room: "HOT HOUSE" },
  29: { timeOfDay: "NIGHT", room: "HOT HOUSE" },
  30: { timeOfDay: "NIGHT", room: "HOT HOUSE" },
  31: { timeOfDay: "NIGHT", room: "HOT HOUSE" },
  32: { timeOfDay: "DAY", room: "BOILER ROOM" },
  33: { timeOfDay: "DAY", room: "BOILER ROOM" },
  34: { timeOfDay: "DAY", room: "BOILER ROOM" },
  35: { timeOfDay: "NIGHT", room: "BOILER ROOM" },
  36: { timeOfDay: "NIGHT", room: "BOILER ROOM" },
  37: { timeOfDay: "NIGHT", room: "BOILER ROOM" },
  38: { timeOfDay: "DAY", room: "LOFT" },
  39: { timeOfDay: "DAY", room: "LOFT" },
  40: { timeOfDay: "DAY", room: "LOFT" },
  41: { timeOfDay: "NIGHT", room: "LOFT" },
  42: { timeOfDay: "NIGHT", room: "LOFT" },
  43: { timeOfDay: "NIGHT", room: "LOFT" },
};
